DROP TABLE IF EXISTS film_likes;
DROP TABLE IF EXISTS user_friends;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS users;

--USERS
CREATE TABLE IF NOT EXISTS users
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255) NOT NULL,
    login character varying(255) NOT NULL,
    name character varying(255),
    birthday date
);

--USER_FRIENDS
CREATE TABLE IF NOT EXISTS user_friends
(
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT friend_uniq_con UNIQUE (user_id, friend_id),
    CONSTRAINT user_not_friend_con CHECK (user_id != friend_id)
);

CREATE INDEX IF NOT EXISTS fki_fk_friend_friend_id
    ON user_friends
        (friend_id ASC NULLS LAST);

CREATE INDEX IF NOT EXISTS fki_fk_friend_user_id
    ON user_friends
        (user_id ASC NULLS LAST);

CREATE UNIQUE INDEX IF NOT EXISTS user_friends_uniq_pk
    ON user_friends
        (user_id ASC NULLS LAST, friend_id ASC NULLS LAST);

--MPA
CREATE TABLE IF NOT EXISTS mpa
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(30)  NOT NULL,
    description character varying(4000)
);

--FILMS
CREATE TABLE IF NOT EXISTS films
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    description character varying(4000),
    release_date date,
    duration smallint,
    mpa INTEGER REFERENCES mpa (id) ON DELETE RESTRICT
);

--FILM_LIKES
CREATE TABLE IF NOT EXISTS film_likes
(
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT like_unic_con UNIQUE (film_id, user_id)
);

CREATE INDEX IF NOT EXISTS fki_fk_like_film_id
    ON film_likes
        (film_id ASC NULLS LAST);

CREATE INDEX IF NOT EXISTS fki_fk_like_user_id
    ON film_likes
        (user_id ASC NULLS LAST);

--GENRES
CREATE TABLE IF NOT EXISTS genres
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL
);

--FILM_GENRES
CREATE TABLE IF NOT EXISTS film_genres
(
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres (id) ON DELETE CASCADE,
    CONSTRAINT film_genre_uniq_con UNIQUE (film_id, genre_id)
);

CREATE INDEX IF NOT EXISTS fki_fk_film_genre_film_id
    ON film_genres
        (film_id ASC NULLS LAST);

CREATE INDEX IF NOT EXISTS fki_fk_film_genre_genre_id
    ON film_genres
        (genre_id ASC NULLS LAST);